// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos; 
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyC8fUGWglErH6TOqjzVu01sEsdCxn4_g',
    appId: '1:418698499040:web:b3723b304c60d99b3c9185',
    messagingSenderId: '418698499040',
    projectId: 'freaking-65973',
    authDomain: 'freaking-65973.firebaseapp.com',
    storageBucket: 'freaking-65973.appspot.com',
    measurementId: 'G-MSGDGDWEQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2VYY92iFvSszm3gQldtXS4JSHQZv1BA',
    appId: '1:418698499040:android:eeaa090ce13a05013c9185',
    messagingSenderId: '418698499040',
    projectId: 'freaking-65973',
    storageBucket: 'freaking-65973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6_iGp552RQ0hFsIZFPtUNspvhAGRqxXk',
    appId: '1:418698499040:ios:ee9f2a4ad90044d63c9185',
    messagingSenderId: '418698499040',
    projectId: 'freaking-65973',
    storageBucket: 'freaking-65973.appspot.com',
    iosBundleId: 'com.example.proyectoFctPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6_iGp552RQ0hFsIZFPtUNspvhAGRqxXk',
    appId: '1:418698499040:ios:ee9f2a4ad90044d63c9185',
    messagingSenderId: '418698499040',
    projectId: 'freaking-65973',
    storageBucket: 'freaking-65973.appspot.com',
    iosBundleId: 'com.example.proyectoFctPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyC8fUGWglErH6TOqjzVu01sEsdCxn4_g',
    appId: '1:418698499040:web:bb47220479551cac3c9185',
    messagingSenderId: '418698499040',
    projectId: 'freaking-65973',
    authDomain: 'freaking-65973.firebaseapp.com',
    storageBucket: 'freaking-65973.appspot.com',
    measurementId: 'G-7VGJRE6MMN',
  );
}
